import { AlertTriangle, Star, TrendingUp,FileText, Target, CheckCircle } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Link, useParams } from "react-router-dom";
import DashboardLayout from "@/components/dashboard/DashboardLayout";
import jsPDF from "jspdf";
import { useGetPredictionQuery } from "@/redux/api/predictionApi";

const DashboardResults = () => {

  const { ideaId } = useParams();

  const { data, isLoading, error } = useGetPredictionQuery(ideaId);

  if (isLoading) return <p>Loading...</p>;
  if (error) return <p>Error loading prediction</p>; 
  console.log("DATA:", data?.data);
  console.log("ERROR:", error);
  console.log("LOADING:", isLoading);

   const generatePDFReport = () => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(22);
    doc.setTextColor(0, 150, 136);
    doc.text("Startup Idea Analysis Report", 20, 25);
    
    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 35);
    
    // Scores Section
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Analysis Scores", 20, 50);
    
    doc.setFontSize(12);
    doc.text("Viability Score: 85%", 25, 62);
    doc.text("Market Fit: 72%", 25, 72);
    doc.text("Innovation Score: 90%", 25, 82);
    
    // Risks Section
    doc.setFontSize(16);
    doc.text("Potential Risks", 20, 100);
    
    doc.setFontSize(12);
    doc.text("1. Competitors", 25, 112);
    doc.setFontSize(10);
    doc.text("   Identify main competitors and their advantages", 25, 120);
    
    doc.setFontSize(12);
    doc.text("2. Market Trends", 25, 132);
    doc.setFontSize(10);
    doc.text("   Analyze current market trends and shifts", 25, 140);
    
    // Suggestions Section
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Suggestions", 20, 158);
    
    doc.setFontSize(10);
    const suggestions = [
      "1. Focus on a niche market segment to reduce competition",
      "2. Build MVP and test with early adopters before scaling",
      "3. Consider strategic partnerships for faster market entry"
    ];
    
    suggestions.forEach((suggestion, index) => {
      doc.text(suggestion, 25, 170 + (index * 10));
    });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Start Up Mentor", 20, 280);
    
    // Save the PDF
    doc.save("startup-analysis-report.pdf");
  };

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Analysis Score Card */}
        <Card className="p-6 bg-gradient-to-br from-cyan-400/10 to-purple-500/10 border-cyan-400/20 shadow-lg">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-400 to-purple-500 flex items-center justify-center shadow-lg">
              <TrendingUp className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-bold bg-gradient-to-r from-cyan-500 to-purple-500 bg-clip-text text-transparent">
                Analysis Results
              </h2>
              <p className="text-muted-foreground">Your idea has been analyzed ✨</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-4 rounded-xl bg-background/50 border border-border/50 text-center">
              <div className="text-3xl font-bold text-cyan-500 mb-1">{data?.viabilityScore}%</div>
              <div className="text-sm text-muted-foreground">Viability Score</div>
            </div>
            <div className="p-4 rounded-xl bg-background/50 border border-border/50 text-center">
              <div className="text-3xl font-bold text-purple-500 mb-1">{data?.marketFit}%</div>
              <div className="text-sm text-muted-foreground">Market Fit</div>
            </div>
            <div className="p-4 rounded-xl bg-background/50 border border-border/50 text-center">
              <div className="text-3xl font-bold text-pink-500 mb-1">{data?.innovationScore}%</div>
              <div className="text-sm text-muted-foreground">Innovation Score</div>
            </div>
          </div>
        </Card>

        {/* Potential Risks Card */}
        <Card className="p-6 bg-gradient-to-br from-pink-300/5 to-destructive/5 border-pink-300/20 shadow-lg">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-pink-500/20 to-destructive/20 flex items-center justify-center">
              <AlertTriangle className="w-6 h-6 text-pink-600" />
            </div>
            <h2 className="text-xl font-bold text-card-foreground">Potential Risks</h2>
          </div>

          <div className="space-y-4">
            {data?.risks?.map((risk, index) => (
              <div key={index}>
                <h3 className="font-semibold mb-2">
                  {index + 1}.
                </h3>
                <div className="p-4 rounded-xl bg-background/50 border border-border/50 text-muted-foreground">
                  {risk}
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Suggestions Card */}
        <Card className="p-6 bg-gradient-to-br from-cyan-400/5 to-purple-500/5 border-cyan-400/20 shadow-lg">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-400 to-purple-500 flex items-center justify-center shadow-lg">
              <Star className="w-6 h-6 text-white" />
            </div>
            <h2 className="text-xl font-bold text-card-foreground">Suggestions</h2>
          </div>

          <div className="space-y-4">
          {data?.suggestions?.map((suggestion, num) => (
            <div key={num}>
              <h3 className="font-semibold mb-2">
                {num + 1}.
              </h3>
              <div className="p-4 rounded-xl bg-gradient-to-r from-purple/10 to-pink/10 border border-purple/20 text-muted-foreground">
                {suggestion}
              </div>
            </div>
          ))}
        </div>
        </Card>

        {/* Action Buttons */}
        <div className="flex gap-4">
          <Link to="/dashboard/submit-idea" className="flex-1">
            <Button variant="outline" className="w-full py-6">
              Submit Another Idea
            </Button>
          </Link>
           <Button 
            onClick={generatePDFReport}
            className="flex-1 gradient-button text-white py-6"
          >
            <FileText className="w-5 h-5 mr-2" />
            Generate Report
          </Button>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default DashboardResults;
